<a href="https://colab.research.google.com/github/shubhammadane/pandas-by-shubhammadane/blob/main/Machine_Learning_Day_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**AI vs ML vs DL**
===================
What is AI? Give a real-time example.
------------------------------------------
AI is the technology that makes machines think and act like humans. It can make decisions, solve problems, and understand language.
Real-time: Google Maps traffic prediction, chatbots, voice assistants.

What is ML? How is it used in real life?
-----------------------------------------------
Machine Learning is a part of AI where systems learn from data and improve automatically without programming rules.
Real-time: Gmail spam filter learns from emails and blocks spam.

What is Deep Learning?
--------------------------------------
Deep Learning is a subset of ML that uses multi-layer neural networks to learn complex patterns from large data.
Real-time: Face recognition, medical image detection.


Difference between AI, ML, DL?
---------------------------------
AI is the broad field. ML is AI that learns from data. DL is ML using deep neural networks.
Real-time:

AI → Chatbot

ML → Movie recommendation

DL → Self-driving car vision

What is Linear Regression?
==================================

Linear Regression is a Machine Learning algorithm used to find a straight-line relationship between:

Input (X) → independent variable

Output (Y) → dependent variable

It answers questions like:

If X increases, how does Y change?

Why Linear Regression?
--------------------------
Because in real life:

Higher CGPA → generally higher package

More study hours → more marks

More experience → higher salary

This relationship is not perfect, but approximately linear
That’s why your image says “sort of linear”

The straight line is written as:


    y=mx+b
y → Output (Target)

What we want to predict

In your image: Package

Example:

“What package will a student get?”

2️⃣ x → Input (Feature)

What we already know

In your image: CGPA

Example:

“Student CGPA = 7.5”

3️⃣ m → Slope

Slope = how fast y changes when x changes

👉 Meaning:

If CGPA increases by 1, how much does package increase?

Example:

m = 0.5

CGPA ↑ by 1 → Package ↑ by 0.5 LPA

That’s why on the image it’s written:
m → slope

4️⃣ b → Y-intercept

b = value of y when x = 0

👉 Meaning:

Base value

Starting point of the line

Example:

Even if CGPA were 0 (theoretical), package might start at some base value.

That’s why it’s written:
b → y-intercept	​



In [37]:
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

In [38]:
df =  pd.read_csv('/content/Dataset/placement.csv')
df.head()


cgpa  package
0  6.89     3.26
1  5.12     1.98
2  7.82     3.25
3  7.42     3.67
4  6.94     3.57

In [39]:
#scatter plot is a graph used to show the relationship between two numerical variables.
#X-axis → CGPA
#Y-axis → Package (Salary)
#Each dot = One student’s data

plt.scatter(df['cgpa'],df['package'])
plt.xlabel('CGPA')
plt.ylabel('Package in LPA')


Text(0, 0.5, 'Package in LPA')

In [40]:
x = df.iloc[:,0:1]
y = df.iloc[:,-1]
# What is iloc ?
# ---------------
# iloc = Index Location
# It is used to select data from a DataFrame using row and column numbers (indexes) — not names.
# Format:
# df.iloc[row_selection , column_selection]



In [41]:
y

0      3.26
1      1.98
2      3.25
3      3.67
4      3.57
       ... 
195    2.46
196    2.57
197    3.24
198    3.96
199    2.33
Name: package, Length: 200, dtype: float64

In [42]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=2)

In [43]:
from sklearn.linear_model import LinearRegression

In [44]:
lr = LinearRegression()

In [45]:
lr.fit(x_train,y_train)

LinearRegression()

In [46]:
x_test

cgpa
112  8.58
29   7.15
182  5.88
199  6.22
193  4.57
85   4.79
10   5.32
54   6.86
115  8.35
35   6.87
12   8.94
92   7.90
13   6.93
126  5.91
174  7.32
2    7.82
44   5.09
3    7.42
113  6.94
14   7.73
23   6.19
25   7.28
6    6.73
134  7.20
165  8.21
173  6.75
45   7.87
65   7.60
48   8.63
122  5.12
178  8.15
64   7.36
9    8.31
57   6.60
78   6.59
71   7.47
128  7.93
176  6.29
131  6.37
53   6.47

In [47]:
y_test

112    4.10
29     3.49
182    2.08
199    2.33
193    1.94
85     1.48
10     1.86
54     3.09
115    4.21
35     2.87
12     3.65
92     4.00
13     2.89
126    2.60
174    2.99
2      3.25
44     1.86
3      3.67
113    2.37
14     3.42
23     2.48
25     3.65
6      2.60
134    2.83
165    4.08
173    2.56
45     3.58
65     3.81
48     4.09
122    2.01
178    3.63
64     2.92
9      3.51
57     1.94
78     2.21
71     3.34
128    3.34
176    3.23
131    2.01
53     2.61
Name: package, dtype: float64

In [48]:
lr.predict(x_test.iloc[0].values.reshape(1,1))

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([3.89111601])

In [49]:
plt.scatter(df['cgpa'],df['package'])
plt.plot(x_train,lr.predict(x_train),color='Black')
plt.xlabel('CGPA')
plt.ylabel('Package(in lpa)')


Text(0, 0.5, 'Package(in lpa)')

In [50]:
m = lr.coef_

In [51]:
b = lr.intercept_

In [52]:
m * 6.35 + b

array([2.64688311])

In [53]:
m * 100 + b

array([54.89908542])