<a href="https://colab.research.google.com/github/shubhammadane/pandas-by-shubhammadane/blob/main/Numpy_Python_by_Shubham_Madane.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Installation of numpy

In [1]:
! pip install numpy

In [2]:
import numpy as np

In [3]:
np.__version__#Check the Vesion

'2.0.2'

In [4]:
list1=[1,2,3,4,5]
list1

[1, 2, 3, 4, 5]

In [6]:
arrlist = np.array(list1)
print(arrlist)

[1 2 3 4 5]


In [7]:
print(type(arrlist))

<class 'numpy.ndarray'>


In [8]:
arrlist.ndim #Check the Arrays type

1

In [11]:
list1=[1,2,3,4,5]
list2=[2,3,4,5,6]
arr2d= np.array([list1,list2])
print(arr2d)

[[1 2 3 4 5]
 [2 3 4 5 6]]


In [12]:
print(arr2d.ndim)

2


In [13]:
list1 = [11,22,33,44]
list2 = [22,33,44,55]
list3 = [33,44,55,66]

arr3d = np.array([[list1,list2,list3]])
print(arr3d)

[[[11 22 33 44]
  [22 33 44 55]
  [33 44 55 66]]]


In [14]:
print(arr3d.ndim)

3


In [15]:
arr1= np.array([[11,22,33,44],[33,4,5,55,]])
print(arr1)

[[11 22 33 44]
 [33  4  5 55]]


In [20]:
print("Shape: ",arr1.shape)
print("Size: ",arr1.size)
print("Dimension: ",arr1.ndim)
print("Datatype: ",arr1.dtype)
print("Check Type: ",type(arr1))

Shape:  (2, 4)
Size:  8
Dimension:  2
Datatype:  int64
Check Type:  <class 'numpy.ndarray'>
