<a href="https://colab.research.google.com/github/shubhammadane/pandas-by-shubhammadane/blob/main/Numpy_Revision_by_Shubham_Madane_30_01_26.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!pip install numpy


In [3]:
import numpy as np
list = [11,222,33,4,44,43]
print(list)
# Characteristics of Python List:
# Can store different data types
# Slower for mathematical operations
# Uses more memory
# Operations require loops
# Built-in Python data structure

[11, 222, 33, 4, 44, 43]


In [5]:
data = np.array(list)
data

# Characteristics of NumPy Array:
# Stores same data type only
# Very fast (written in C)
# Less memory usage
# Supports vectorized operations
# Designed for numerical computing

array([ 11, 222,  33,   4,  44,  43])

In [6]:
print(type(data))

<class 'numpy.ndarray'>


**What is a 1D Array in NumPy? (Interview Answer)**

Definition:
A 1D array in NumPy is a one-dimensional list of elements stored in a single row, where all elements are of the same data type. It is created using numpy.array() and is mainly used for fast numerical computation.

In [8]:
import numpy as np
name= ['Shuhbham','Ram','Vaibhav','Suyash']
data = np.array(name)
print(data)
print(type(data))
print(type(name))

['Shuhbham' 'Ram' 'Vaibhav' 'Suyash']
<class 'numpy.ndarray'>
<class 'list'>


In [11]:
#Real-Time Example: Student Marks Analysis
import numpy as np
mark = np.array([85,96,87,75,73])
avg= np.mean(mark)
updated = mark + 2
print("Avg: ",avg)
print("Updated Marks: ",updated)

Avg:  83.2
Updated Marks:  [87 98 89 77 75]


In [13]:
#Real-Time Example
import numpy as np
temp = np.array([35,41,38,42,36])
print("Max Temp: ",temp.max())
print("Min Temp: ",temp.min() )
print("Avg Temp: ",temp.mean() )

Max Temp:  42
Min Temp:  35
Avg Temp:  38.4


**What is a 2D (Two-Dimensional) Array in NumPy?**

A 2D array in NumPy is a data structure arranged in rows and columns, similar to a table or matrix, where all elements are of the same data type.


A 2D array in NumPy is a matrix-like structure with rows and columns, commonly used to represent tables, images, and numerical datasets.

In [17]:
import numpy as np
data = np.array([[11,22,33,44],
                [44,55,66,77]])
print(data)
print(type(data))
print(data[1][0])
print(data[0][1])


# 2 rows
# 4 columns
# Shape = (2, 3)

[[11 22 33 44]
 [44 55 66 77]]
<class 'numpy.ndarray'>
44
22


In [22]:
#Creating the Arrays:
list1 = [11,22,33,44,55,66]
list2 = [21,32,43,54,65,67]
addList = np.array([[list1],[list2]])
print(addList)
print(list1 + list2)

[[[11 22 33 44 55 66]]

 [[21 32 43 54 65 67]]]
[11, 22, 33, 44, 55, 66, 21, 32, 43, 54, 65, 67]


***what is 3D Array?***

 A 3D array is a data structure that stores elements in three dimensions, organized as a collection of 2D arrays stacked together.

**One-Line Interview Explanation**

 A 3D array stores data as a stack of 2D matrices, represented using Depth × Rows × Columns, commonly used in images, videos, and deep learning.

In [25]:
import numpy as np
data = np.array([[[11,22,33,44],
                [1,2,3,4],
                [21,32,43,54]]])
print(data)
print(type(data))
data.shape

[[[11 22 33 44]
  [ 1  2  3  4]
  [21 32 43 54]]]
<class 'numpy.ndarray'>


(1, 3, 4)

In [47]:
data = np.array([
                 [[11,22,33,44],
                 [1,2,3,4],
                 [21,32,43,54]],

                 [[23,43,45,65],
                 [34,54,65,22],
                 [77,22,32,22]]
                 ])
print(data)
print(type(data))
data.shape

print(data[1][2][3])
print(data[0][1][3])


# What Does (2, 3, 4) Mean?Shape of an array defines the number of elements in each dimension (axis) of the array.
#  Dimension	     Meaning
#  2	         Number of blocks / samples
#  3	         Rows in each block
#  4	         Columns in each row


#==============
# data[1] → 2nd block

# [1] → 2nd row

# [3] → 4th column

[[[11 22 33 44]
  [ 1  2  3  4]
  [21 32 43 54]]

 [[23 43 45 65]
  [34 54 65 22]
  [77 22 32 22]]]
<class 'numpy.ndarray'>
22
4


In [50]:
#3D Array for a Color Image (RGB)
color = np.array([
    [[255,0,16],
     [244,255,0]],

    [[255,0,211],
    [244,155,201]]
    ])
print(color)
print(color.shape)

[[[255   0  16]
  [244 255   0]]

 [[255   0 211]
  [244 155 201]]]
(2, 2, 3)


In [51]:
#: Video Frames as a 3D Array
import numpy as np

# 3 video frames, each of size 2x2
video = np.array([
    [[10, 20],
     [30, 40]],

    [[50, 60],
     [70, 80]],

    [[90, 100],
     [110, 120]]
])

print("Video Frames:")
print(video)
print("Shape:", video.shape)


Video Frames:
[[[ 10  20]
  [ 30  40]]

 [[ 50  60]
  [ 70  80]]

 [[ 90 100]
  [110 120]]]
Shape: (3, 2, 2)


**NumPy Array Attributes**

Attributes describe the array itself (not actions like functions).

In [59]:
# Real-Time Use:
# Determines if data is 1D sensor readings, 2D table or image, or 3D video frames.
# Used before reshaping data for ML models.
# Interview Tip:
# “ndim tells how many axes the array has, which is crucial for knowing how to process or feed data into models.”

import numpy as np
data = np.array([11,22,33,44])
print(data.ndim)
data2 = np.array([[11,22,33,44],[22,33,55,66]])
print(data2.ndim)
data3 = np.array([[[11,22,33,44],
             [21,2,12,32],
             [32,44,55,66]]])
print(data3.ndim)


1
2
3
4


In [60]:
# size – Total Number of Elements
# What it is: Total number of elements in the array (product of all dimensions).
# Real-Time Example:
# Flattening a 64×64 image gives 4096 pixels.
# Helps verify dataset completeness or perform data normalization.
import numpy as np
data = np.array([11,22,33,44])
print(data.size)
data2 = np.array([[11,22,33,44],[22,33,55,66]])
print(data2.size)
data3 = np.array([[[11,22,33,44],
             [21,2,12,32],
             [32,44,55,66]]])
print(data3.size)

4
8
12


In [61]:
# shape – Size of Each Dimension
# What it is: Shows the size along each dimension as a tuple.
# Real-Time Example:
# A dataset of 100 images, each 64×64 pixels, would have shape (100, 64, 64).
# Important for ensuring ML models receive the correct input size.

import numpy as np
data = np.array([11,22,33,44])
print(data.shape)
data2 = np.array([[11,22,33,44],[22,33,55,66]])
print(data2.shape)
data3 = np.array([[[11,22,33,44],
             [21,2,12,32],
             [32,44,55,66]]])
print(data3.shape)

(4,)
(2, 4)
(1, 3, 4)


In [62]:
import numpy as np
data = np.array([11,22,33,44])
print(type(data))
data2 = np.array([[11,22,33,44],[22,33,55,66]])
print(type(data))
data3 = np.array([[[11,22,33,44],
             [21,2,12,32],
             [32,44,55,66]]])
print(type(data))

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


In [64]:
#itemsize – Memory size of each element (bytes)
import numpy as np
data = np.array([11,22,33,44])
print(data.itemsize)
data2 = np.array([[11,22,33,44],[22,33,55,66]])
print(data2.itemsize)
data3 = np.array([[[11,22,33,44],
             [21,2,12,32],
             [32,44,55,66]]])
print(data3.itemsize)


8
8
8


In [65]:
#nbytes – Total memory usage
import numpy as np
data = np.array([11,22,33,44])
print(data.nbytes)
data2 = np.array([[11,22,33,44],[22,33,55,66]])
print(data2.nbytes)
data3 = np.array([[[11,22,33,44],
             [21,2,12,32],
             [32,44,55,66]]])
print(data3.nbytes)


32
64
96


In [67]:
# T – Transpose of the Array
# What it is: Swaps rows and columns.

import numpy as np
data = np.array([11,22,33,44])
print(data.T)
print("=====================")
data2 = np.array([[11,22,33,44],[22,33,55,66]])
print(data2.T)
print("=====================")
data3 = np.array([[[11,22,33,44],
             [21,2,12,32],
             [32,44,55,66]]])
print(data3.T)


[11 22 33 44]
[[11 22]
 [22 33]
 [33 55]
 [44 66]]
[[[11]
  [21]
  [32]]

 [[22]
  [ 2]
  [44]]

 [[33]
  [12]
  [55]]

 [[44]
  [32]
  [66]]]


In [71]:
#Zero Arrays:
# What:
# Creates an array of a given shape filled with 0s.
# Why:
# Often used to initialize arrays where you’ll later store values.
# Helps avoid garbage values when creating arrays.
import numpy as np
zeroArr = np.zeros((2,3))
print(zeroArr)


[[0. 0. 0.]
 [0. 0. 0.]]


In [74]:
zeroArr = np.zeros((2,3,4))
print(zeroArr)

[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]


In [77]:
# What:
# Creates an array of a given shape filled with any number you want.
# Why:
# Flexible array initialization with a custom value.
# Useful when you need a starting array with a specific constant, like a bias in ML or padding a grid.
full = np.full((2,3),7)
print(full)

[[7 7 7]
 [7 7 7]]


In [78]:
arr = np.ones((2, 3))
print(arr)


[[1. 1. 1.]
 [1. 1. 1.]]


In [88]:
data = np.arange(2, 10, 2)
data1 = np.linspace(2, 10, 5)
print(data)
print(data1)

[2 4 6 8]
[ 2.  4.  6.  8. 10.]


In [120]:
data = np.random.rand(2,4)
print(data)
data1 = np.random.randint(2,100)
data1

[[0.56139726 0.73954244 0.89653326 0.90585628]
 [0.13515477 0.35852214 0.25555724 0.4655782 ]]


33